### PR TITLE
consolidate css/js files

### PR DESCRIPTION
**Pull request by vietnogi**
ping @appirio-tech/demandside

### CODE REVIEW

**Comment by aselbie** [comment]
I'm getting a bunch of SCSS errors when I try to serve it up, all variations on:

```
[10:39:28] SCSS error
{ '0':
   { status: 1,
     file: '/Users/andrewselbie/code/work-app/src/client/app/submit-work/features/styles/features.scss',
     line: 8,
     column: 15,
     message: '10px*px is not a valid CSS value',
     code: 1 } }
```

**Comment by vietnogi** [comment]
try a fresh npm install

**Comment by vietnogi** [comment]
a good indicator for bower/npm install is Travis passing.

**Comment by aselbie** [comment]
Thanks. Any idea which package was causing the SCSS errors?

LGTM.

**Pull request merged**
