### PR TITLE
Update index.html

### PR DESCRIPTION
**Pull request by fnisen**
Added Heap Analytics tracking script

### CODE REVIEW

**Comment by deepanprabhu** [comment]
Filipp, checking in code :+1: Guys, i am still on apprio's code base. Kindly remove me from the organization ( for now :) ) .

**Comment by fnisen** [comment]
@deepanprabhu you see what it's come to?! We're getting desperate over here. : )

**Comment by parthshah** [comment]
👍  merging

**Comment by fnisen** [comment]
@deepanprabhu Parth rightly tells me it's a public repo. You're actually not part of the organization, so you can drop off if you want.

**Comment by deepanprabhu** [comment]
oh nice, thanks @parthshah and @fnisen . Happy coding !!

**Pull request merged**
